### ISSUE TITLE
안녕하세요

### ISSUE THREAD

**Issue by seongmin-97** [jbose038/naver-movie-recommendation#1]
안녕하세요! 
저는 프로그래밍에 대해 조금씩 알아가면서 배우고 있는, 김성민이라고 합니다.
네이버 영화 데이터에서 추천 시스템을 만들어서 안드로이드 어플리케이션에
접목해보고자 검색을 하던 중 이 레포지터리를 발견했습니다.
jbose038님의 코드와 Readme.md의 설명이 너무 잘 되어 있어서 참고하려고 하는데
괜찮으실까요?
혹시 몰라서 글 남깁니다. 어디다 남길지 몰라서 issue에...

**Comment by jbose038** [comment]
최근 업데이트를 하지 않아서 크롤링하는 노트북파일같은 것들이 정상작동하지 않을 수도 있지만 도움이 되신다면 얼마든지 참고하셔도 괜찮습니다!
하고 계시는 앱 개발 성공적으로 완성하시길 기원하겠습니다!

**Comment by seongmin-97** [comment]
감사합니다!!
